/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                    'rgb(var(--primary))',
        'on-primary':                 'rgb(var(--on-primary))',
        'background':                 'rgb(var(--background))',
        'on-background':              'rgb(var(--on-background))',
        'surface':                    'rgb(var(--surface))',
        'on-surface':                 'rgb(var(--on-surface))',
        'surface-container':          'rgb(var(--surface-container))',
        'surface-container-low':      'rgb(var(--surface-container-low))',
        'surface-container-high':     'rgb(var(--surface-container-high))',
        'outline':                    'rgb(var(--outline))',
        'outline-variant':            'rgb(var(--outline-variant))',
        'error':                      'rgb(var(--error))',
        
        // Mantener algunos variantes fijos para compatibilidad o ajustarlos luego
        'surface-variant':            '#f4ede1',
        'on-primary-container':       '#2c1a0a',
        'primary-container':          '#d4af37',
        'secondary':                  '#5d3a28',
        'on-surface-variant':         '#5a4d3f',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'primary-fixed':              '#e2bd6c',
        'surface-container-highest':  '#e8e1d5',
        'on-secondary-container':     '#4a2c1d',
        'secondary-fixed-dim':        '#c28b6d',
        'surface-container-lowest':   '#ffffff',
        'inverse-on-surface':         '#fff1e0',
        'surface-tint':               '#8e6d3c',
        'secondary-fixed':            '#f0d5c8',
        'surface-dim':                '#e8e0d4',
        'primary-fixed-dim':          '#c6a354',
        'secondary-container':        '#d8a48c',
        'tertiary-fixed-dim':         '#d2b9b2',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#e8d5cf',
        'tertiary-fixed':             '#fbeae6',
        'on-tertiary-fixed-variant':  '#54433f',
        'on-primary-fixed':           '#2c1a0a',
        'on-secondary-fixed-variant': '#5d3a28',
        'surface-bright':             '#fdfaf5',
        'inverse-surface':            '#3b3026',
        'on-secondary-fixed':         '#2c160e',
        'on-tertiary-container':      '#3e2d28',
        'tertiary':                   '#7b5850',
        'on-primary-fixed-variant':   '#6c5123',
        'on-error-container':         '#410002',
        'on-secondary':               '#ffffff',
        'inverse-primary':            '#e2bd6c',
        'on-tertiary-fixed':          '#2d1612',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:     '0.25rem',
        xl:     '0.5rem',
        '2xl':  '1rem',
        '3xl':  '1.5rem',
        full:   '9999px',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
